version: "2"
services:
  web:
    build: .
    environment:
      - MODE
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ../../data/db:/data/db